"""criando tabela jogadores corrigida

Revision ID: 0e34e4b99681
Revises: f8bea231de12
Create Date: 2026-06-16 19:03:53.486879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e34e4b99681'
down_revision = 'f8bea231de12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('posicao', sa.String(length=50), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogador')
    # ### end Alembic commands ###
