"""DATABASE

Revision ID: 19f644d48bba
Revises: 
Create Date: 2026-06-17 09:37:38.747116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f644d48bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competicao', sa.String(), nullable=True),
    sa.Column('colocacao', sa.Integer(), nullable=True),
    sa.Column('premiacao', sa.Integer(), nullable=True),
    sa.Column('num_jogos', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.String(length=50), nullable=False),
    sa.Column('numero_camisa', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('valor_mercado', sa.Float(), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor_transacao', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('jogador')
    op.drop_table('competicoes')
    # ### end Alembic commands ###
