"""mensagem descrevendo a alteração

Revision ID: 1e224e1cb553
Revises: 
Create Date: 2026-06-09 22:49:55.139766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e224e1cb553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competicoes', sa.String(), nullable=True),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competicoes')
    # ### end Alembic commands ###
