"""novo db

Revision ID: 20d28fab5306
Revises: 
Create Date: 2026-06-20 14:24:55.379222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d28fab5306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competicao', sa.String(), nullable=True),
    sa.Column('colocacao', sa.Integer(), nullable=True),
    sa.Column('premiacao', sa.Integer(), nullable=True),
    sa.Column('num_jogos', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('posicao', sa.String(length=50), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('historico', sa.String(length=500), nullable=True),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor_transacao', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    op.drop_table('transacao')
    op.drop_table('jogador')
    op.drop_table('competicoes')
    # ### end Alembic commands ###
