"""mensagem descrevendo a alteração

Revision ID: 22001984b0a8
Revises: 64c8699ee387
Create Date: 2026-06-10 09:09:34.841612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22001984b0a8'
down_revision = '64c8699ee387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competicao', sa.String(), nullable=True))
        batch_op.drop_column('competicoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competicoes', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('competicao')

    # ### end Alembic commands ###
