"""inicial

Revision ID: 2dce48a8ec30
Revises: 
Create Date: 2026-06-16 22:06:49.540160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dce48a8ec30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('posicao', sa.String(length=50), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('historico', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    op.drop_table('jogador')
    op.drop_table('competicoes')
    # ### end Alembic commands ###
