"""empty message

Revision ID: 311db2fa2d02
Revises: 9a706e197321
Create Date: 2026-06-23 17:35:33.118889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311db2fa2d02'
down_revision = '9a706e197321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_atleta', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('posicao_atleta', sa.String(length=50), nullable=False))
        batch_op.drop_column('nome')
        batch_op.drop_column('posicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('posicao_atleta')
        batch_op.drop_column('nome_atleta')

    # ### end Alembic commands ###
