"""adição data transacao

Revision ID: 601412313936
Revises: 3a216a344ce0
Create Date: 2026-06-11 00:11:47.221146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601412313936'
down_revision = '3a216a344ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_transacao', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_column('data_transacao')

    # ### end Alembic commands ###
