"""criando tabela competicoes

Revision ID: 64c8699ee387
Revises: 1e224e1cb553
Create Date: 2026-06-10 08:45:05.997384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c8699ee387'
down_revision = '1e224e1cb553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colocacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vitorias', sa.Integer(), nullable=True))
        batch_op.drop_column('posicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao', sa.INTEGER(), nullable=True))
        batch_op.drop_column('vitorias')
        batch_op.drop_column('colocacao')

    # ### end Alembic commands ###
