"""nova tabela

Revision ID: 7d861bb60b94
Revises: 22001984b0a8
Create Date: 2026-06-11 12:26:25.445736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d861bb60b94'
down_revision = '22001984b0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brasileirao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brasileirao')
    # ### end Alembic commands ###
