"""adição ao db jogadores

Revision ID: b87f3caf3e2a
Revises: e9a9711a7645
Create Date: 2026-06-09 21:21:19.966033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87f3caf3e2a'
down_revision = 'e9a9711a7645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_mercado', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('salario', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.drop_column('salario')
        batch_op.drop_column('valor_mercado')

    # ### end Alembic commands ###
