"""Ta funcionando agora eu acho

Revision ID: ffa14d854e23
Revises: 
Create Date: 2026-06-16 21:17:47.278577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa14d854e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competicao', sa.String(), nullable=True),
    sa.Column('colocacao', sa.Integer(), nullable=True),
    sa.Column('premiacao', sa.Integer(), nullable=True),
    sa.Column('num_jogos', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competicoes')
    # ### end Alembic commands ###
